import { View, Text, TouchableOpacity, ScrollView } from 'react-native';
import React, { useState } from 'react';
import { AppLayout, InputField, PlayerCard } from '../../components';

type Player = {
  id: number;
  name: string;
  last_name: string;
  age: number;
};
type FormValues = {
  teamName: string;
  age: number;
  players: Player[];
};

const TeamCreationPage: React.FC = () => {
  const [selectedPlayers, setSelectedPlayers] = useState<Player[]>([]);
  const allPlayers: Player[] = [{"id":1,"name":"Derron","last_name":"Vignal","age":15},
    {"id":2,"name":"Illa","last_name":"Farlamb","age":12},
    {"id":3,"name":"Bambi","last_name":"Litchmore","age":11},
    {"id":4,"name":"Cordy","last_name":"Andrichak","age":16},
    {"id":5,"name":"Annabell","last_name":"Lacknor","age":14},
    {"id":6,"name":"Marrilee","last_name":"Gilby","age":12},
    {"id":7,"name":"Vic","last_name":"Sharnock","age":12},
    {"id":8,"name":"Chelsie","last_name":"Myott","age":15},
    {"id":9,"name":"Barney","last_name":"Gamwell","age":13},
    {"id":10,"name":"Alisander","last_name":"Straw","age":15},
    {"id":11,"name":"Loralyn","last_name":"Batisse","age":11},
    {"id":12,"name":"Gilda","last_name":"Grocock","age":18},
    {"id":13,"name":"Paquito","last_name":"Bonehill","age":17},
    {"id":14,"name":"Inglis","last_name":"Jeannin","age":17},
    {"id":15,"name":"Constance","last_name":"Mauger","age":13},
    {"id":16,"name":"Giffie","last_name":"Brandrick","age":10},
    {"id":17,"name":"Benedick","last_name":"Mayoral","age":10},
    {"id":18,"name":"Corabelle","last_name":"Loukes","age":14},
    {"id":19,"name":"Elvin","last_name":"Klyner","age":14},
    {"id":20,"name":"Daphna","last_name":"Cullnean","age":15},
    {"id":21,"name":"Zachariah","last_name":"Cammomile","age":14},
    {"id":22,"name":"Sullivan","last_name":"Revens","age":17},
    {"id":23,"name":"Maryjane","last_name":"Muslim","age":17},
    {"id":24,"name":"Nickola","last_name":"Hammon","age":11},
    {"id":25,"name":"Luis","last_name":"Haskins","age":16},
    {"id":26,"name":"Dennet","last_name":"Crumb","age":13},
    {"id":27,"name":"Cathlene","last_name":"Luchelli","age":10},
    {"id":28,"name":"Maighdiln","last_name":"Sapson","age":18},
    {"id":29,"name":"Reinold","last_name":"Casarini","age":17},
    {"id":30,"name":"Emery","last_name":"Amber","age":14},
    {"id":31,"name":"Dallas","last_name":"Enbury","age":13},
    {"id":32,"name":"Dara","last_name":"Ixer","age":16},
    {"id":33,"name":"Amalita","last_name":"Maden","age":10},
    {"id":34,"name":"Ivor","last_name":"Andrys","age":13},
    {"id":35,"name":"Nance","last_name":"Bramstom","age":14},
    {"id":36,"name":"Rhetta","last_name":"Prisley","age":10},
    {"id":37,"name":"Cecil","last_name":"Gooden","age":18},
    {"id":38,"name":"Tadeo","last_name":"Denniston","age":11},
    {"id":39,"name":"Zuzana","last_name":"Hamblington","age":18},
    {"id":40,"name":"Leandra","last_name":"Laite","age":15},
    {"id":41,"name":"Neall","last_name":"Gehricke","age":10},
    {"id":42,"name":"Cecelia","last_name":"Bollam","age":18},
    {"id":43,"name":"Gardy","last_name":"Searchfield","age":13},
    {"id":44,"name":"Sully","last_name":"Etches","age":12},
    {"id":45,"name":"Aurlie","last_name":"Kleehuhler","age":13},
    {"id":46,"name":"Cassandre","last_name":"Dossett","age":13},
    {"id":47,"name":"Pen","last_name":"Hacker","age":11},
    {"id":48,"name":"Maurice","last_name":"Hobbert","age":10},
    {"id":49,"name":"Christi","last_name":"Barthelmes","age":15},
    {"id":50,"name":"Norton","last_name":"Prigmore","age":15},
    {"id":51,"name":"Carly","last_name":"Savaage","age":15},
    {"id":52,"name":"Pascale","last_name":"McConnulty","age":12},
    {"id":53,"name":"Arnaldo","last_name":"Rowler","age":18},
    {"id":54,"name":"Emmaline","last_name":"Mayers","age":11},
    {"id":55,"name":"Celina","last_name":"Drummond","age":14},
    {"id":56,"name":"Sherlocke","last_name":"Britzius","age":12},
    {"id":57,"name":"Hayward","last_name":"Thatcham","age":12},
    {"id":58,"name":"Grover","last_name":"Riccione","age":15},
    {"id":59,"name":"Quintin","last_name":"Tripp","age":17},
    {"id":60,"name":"Brandyn","last_name":"Aarons","age":17},
    {"id":61,"name":"Charline","last_name":"Eagar","age":17},
    {"id":62,"name":"Ashien","last_name":"McKall","age":15},
    {"id":63,"name":"Reggi","last_name":"Ledster","age":17},
    {"id":64,"name":"Selie","last_name":"Bartaloni","age":14},
    {"id":65,"name":"Shellysheldon","last_name":"Bridger","age":11},
    {"id":66,"name":"Farrell","last_name":"Mallinson","age":17},
    {"id":67,"name":"Barnabe","last_name":"Borsnall","age":11},
    {"id":68,"name":"Gabbie","last_name":"Tournay","age":13},
    {"id":69,"name":"Brittni","last_name":"Downey","age":14},
    {"id":70,"name":"Van","last_name":"Dyers","age":17},
    {"id":71,"name":"Mina","last_name":"Hazeldene","age":16},
    {"id":72,"name":"Bryana","last_name":"Domoni","age":10},
    {"id":73,"name":"Johanna","last_name":"Hazelgrove","age":13},
    {"id":74,"name":"Patrizio","last_name":"Healeas","age":15},
    {"id":75,"name":"Eilis","last_name":"Geator","age":13},
    {"id":76,"name":"Jackie","last_name":"Ferrer","age":15},
    {"id":77,"name":"Trula","last_name":"MacDowal","age":11},
    {"id":78,"name":"Drona","last_name":"Bilsborrow","age":11},
    {"id":79,"name":"Mathilde","last_name":"Major","age":18},
    {"id":80,"name":"Ingeborg","last_name":"Unstead","age":15},
    {"id":81,"name":"Tana","last_name":"Ecles","age":10},
    {"id":82,"name":"Jayme","last_name":"Pappi","age":12},
    {"id":83,"name":"Connie","last_name":"Karus","age":16},
    {"id":84,"name":"Porty","last_name":"Longea","age":15},
    {"id":85,"name":"Casey","last_name":"Robiou","age":16},
    {"id":86,"name":"Mile","last_name":"Foxen","age":17},
    {"id":87,"name":"Nicolais","last_name":"Cayton","age":11},
    {"id":88,"name":"Leonelle","last_name":"Ambridge","age":17},
    {"id":89,"name":"Ferrell","last_name":"Atwool","age":16},
    {"id":90,"name":"Lenna","last_name":"Grier","age":15},
    {"id":91,"name":"Giffard","last_name":"Canelas","age":17},
    {"id":92,"name":"Marie-ann","last_name":"Hain","age":14},
    {"id":93,"name":"Lian","last_name":"Willoughley","age":14},
    {"id":94,"name":"Lindsay","last_name":"Beney","age":17},
    {"id":95,"name":"Quentin","last_name":"Fisbey","age":18},
    {"id":96,"name":"Gabrila","last_name":"Jenny","age":15},
    {"id":97,"name":"Amandi","last_name":"Alyutin","age":10},
    {"id":98,"name":"Myrlene","last_name":"Crawley","age":12},
    {"id":99,"name":"Lawton","last_name":"Hartrick","age":18},
    {"id":100,"name":"Selina","last_name":"Robertelli","age":16},
    {"id":101,"name":"Joane","last_name":"Blakeway","age":15},
    {"id":102,"name":"Gran","last_name":"MacNeilage","age":11},
    {"id":103,"name":"Hagan","last_name":"Wortt","age":12},
    {"id":104,"name":"Clea","last_name":"Smitham","age":12},
    {"id":105,"name":"Molli","last_name":"Gibbett","age":11},
    {"id":106,"name":"Davida","last_name":"Branchet","age":14},
    {"id":107,"name":"Babette","last_name":"Scrane","age":16},
    {"id":108,"name":"Chelsae","last_name":"Kuschel","age":13},
    {"id":109,"name":"Francesca","last_name":"Espinosa","age":16},
    {"id":110,"name":"Randie","last_name":"Beacham","age":14},
    {"id":111,"name":"Hilliary","last_name":"Krolik","age":14},
    {"id":112,"name":"Dominick","last_name":"Gilliam","age":16},
    {"id":113,"name":"Carolina","last_name":"Noteyoung","age":17},
    {"id":114,"name":"Maryellen","last_name":"Baumann","age":12},
    {"id":115,"name":"Danny","last_name":"Lux","age":17},
    {"id":116,"name":"Ricardo","last_name":"Feeny","age":11},
    {"id":117,"name":"Wally","last_name":"Lumbers","age":10},
    {"id":118,"name":"Dukie","last_name":"Swansbury","age":15},
    {"id":119,"name":"Cesaro","last_name":"Black","age":12},
    {"id":120,"name":"Emmy","last_name":"Lebel","age":18},
    {"id":121,"name":"Lonna","last_name":"Eichmann","age":12},
    {"id":122,"name":"Lawton","last_name":"Winsper","age":10},
    {"id":123,"name":"Niccolo","last_name":"Mayers","age":16},
    {"id":124,"name":"Bartlet","last_name":"McNirlin","age":11},
    {"id":125,"name":"Wilton","last_name":"Iliff","age":13},
    {"id":126,"name":"Peirce","last_name":"Kahan","age":13},
    {"id":127,"name":"Olwen","last_name":"Sommersett","age":15},
    {"id":128,"name":"Leyla","last_name":"Nehls","age":16},
    {"id":129,"name":"Gui","last_name":"Gidden","age":10},
    {"id":130,"name":"Kiri","last_name":"Jerche","age":13},
    {"id":131,"name":"Torrin","last_name":"Puddin","age":17},
    {"id":132,"name":"Clayson","last_name":"Emilien","age":18},
    {"id":133,"name":"Flss","last_name":"Nan Carrow","age":10},
    {"id":134,"name":"Ruthann","last_name":"Normanvill","age":12},
    {"id":135,"name":"Ivory","last_name":"Jeannaud","age":18},
    {"id":136,"name":"Teri","last_name":"Justice","age":12},
    {"id":137,"name":"Carmina","last_name":"Marmion","age":10},
    {"id":138,"name":"Marita","last_name":"Heymann","age":16},
    {"id":139,"name":"Sutton","last_name":"Loudiane","age":16},
    {"id":140,"name":"Cristy","last_name":"Illingsworth","age":10},
    {"id":141,"name":"Hyman","last_name":"Litherland","age":14},
    {"id":142,"name":"Nevsa","last_name":"Torrance","age":17},
    {"id":143,"name":"Clay","last_name":"Fennick","age":12},
    {"id":144,"name":"Alford","last_name":"Jennison","age":18},
    {"id":145,"name":"Vincents","last_name":"Ziemecki","age":14},
    {"id":146,"name":"Corinna","last_name":"Vaggers","age":12},
    {"id":147,"name":"Burke","last_name":"Ashplant","age":16},
    {"id":148,"name":"Bettine","last_name":"Suddards","age":14},
    {"id":149,"name":"Vale","last_name":"Maryin","age":10},
    {"id":150,"name":"Joli","last_name":"Croke","age":11},
    {"id":151,"name":"Terry","last_name":"Ostridge","age":13},
    {"id":152,"name":"Jerry","last_name":"Lodewick","age":10},
    {"id":153,"name":"Shirlene","last_name":"Nairns","age":17},
    {"id":154,"name":"Allsun","last_name":"Cray","age":13},
    {"id":155,"name":"Auroora","last_name":"Hinge","age":16},
    {"id":156,"name":"Giselbert","last_name":"Cuddy","age":10},
    {"id":157,"name":"Clive","last_name":"Bicknell","age":17},
    {"id":158,"name":"Scotti","last_name":"Gresly","age":18},
    {"id":159,"name":"Milka","last_name":"Wickling","age":18},
    {"id":160,"name":"Graeme","last_name":"Ebanks","age":16},
    {"id":161,"name":"Tommy","last_name":"Hearnaman","age":11},
    {"id":162,"name":"Turner","last_name":"Lamdin","age":16},
    {"id":163,"name":"Trevar","last_name":"Kermode","age":18},
    {"id":164,"name":"Ugo","last_name":"Mattioli","age":16},
    {"id":165,"name":"Drud","last_name":"Speake","age":16},
    {"id":166,"name":"Perry","last_name":"Frediani","age":14},
    {"id":167,"name":"Nicol","last_name":"Polkinghorne","age":12},
    {"id":168,"name":"Dietrich","last_name":"Millgate","age":11},
    {"id":169,"name":"Mylo","last_name":"Brackstone","age":12},
    {"id":170,"name":"Elinore","last_name":"Sagerson","age":18},
    {"id":171,"name":"Swen","last_name":"Rodrigues","age":17},
    {"id":172,"name":"Conn","last_name":"Birdfield","age":16},
    {"id":173,"name":"Ibby","last_name":"O'Cannon","age":12},
    {"id":174,"name":"Alister","last_name":"Sperski","age":18},
    {"id":175,"name":"Helenelizabeth","last_name":"Brigdale","age":17},
    {"id":176,"name":"Hillard","last_name":"Meadus","age":10},
    {"id":177,"name":"Marlyn","last_name":"Roney","age":11},
    {"id":178,"name":"Loralyn","last_name":"Gyford","age":13},
    {"id":179,"name":"Marve","last_name":"Elsworth","age":16},
    {"id":180,"name":"Gaynor","last_name":"Copyn","age":11},
    {"id":181,"name":"Fulton","last_name":"Maddison","age":14},
    {"id":182,"name":"Vonny","last_name":"Bratty","age":13},
    {"id":183,"name":"Elton","last_name":"Blowne","age":13},
    {"id":184,"name":"Melitta","last_name":"Bumpus","age":15},
    {"id":185,"name":"Lenette","last_name":"Daveridge","age":13},
    {"id":186,"name":"Gunner","last_name":"Di Napoli","age":14},
    {"id":187,"name":"Marci","last_name":"Marmyon","age":12},
    {"id":188,"name":"Tucker","last_name":"Maynard","age":17},
    {"id":189,"name":"Gordy","last_name":"Grevatt","age":10},
    {"id":190,"name":"Conrad","last_name":"Kerrey","age":10},
    {"id":191,"name":"Alejandro","last_name":"Bresnen","age":11},
    {"id":192,"name":"Dacy","last_name":"Nusche","age":10},
    {"id":193,"name":"Forester","last_name":"Pargeter","age":14},
    {"id":194,"name":"Mora","last_name":"Huggett","age":13},
    {"id":195,"name":"Sherlock","last_name":"Nystrom","age":11},
    {"id":196,"name":"Ryon","last_name":"Trimmell","age":16},
    {"id":197,"name":"Debi","last_name":"Farthin","age":15},
    {"id":198,"name":"Michaela","last_name":"Josiah","age":15},
    {"id":199,"name":"Perl","last_name":"Middup","age":16},
    {"id":200,"name":"Mandy","last_name":"Jedrzej","age":15},
    {"id":201,"name":"Ave","last_name":"Vales","age":13},
    {"id":202,"name":"Wenonah","last_name":"Blitz","age":13},
    {"id":203,"name":"Babbie","last_name":"Flannery","age":18},
    {"id":204,"name":"Jonell","last_name":"Volcker","age":18},
    {"id":205,"name":"Sharon","last_name":"Vaggers","age":10},
    {"id":206,"name":"Harman","last_name":"Coweuppe","age":17},
    {"id":207,"name":"Meredith","last_name":"Breen","age":11},
    {"id":208,"name":"Dun","last_name":"Boniface","age":11},
    {"id":209,"name":"Theo","last_name":"Hannan","age":14},
    {"id":210,"name":"Serena","last_name":"Beane","age":11},
    {"id":211,"name":"Merlina","last_name":"Brendeke","age":11},
    {"id":212,"name":"Anatol","last_name":"Darbishire","age":17},
    {"id":213,"name":"Ase","last_name":"Godson","age":17},
    {"id":214,"name":"Tremain","last_name":"Carlesi","age":12},
    {"id":215,"name":"Gwendolen","last_name":"Ockendon","age":16},
    {"id":216,"name":"Towny","last_name":"Burwin","age":10},
    {"id":217,"name":"Tracey","last_name":"Betts","age":12},
    {"id":218,"name":"Goober","last_name":"Saunders","age":14},
    {"id":219,"name":"Dennis","last_name":"Stapleford","age":12},
    {"id":220,"name":"Anne","last_name":"Berrigan","age":18},
    {"id":221,"name":"Kristos","last_name":"Vasin","age":10},
    {"id":222,"name":"Chad","last_name":"Tapscott","age":11},
    {"id":223,"name":"Goldy","last_name":"Bigley","age":12},
    {"id":224,"name":"Poul","last_name":"Ingraham","age":16},
    {"id":225,"name":"Rachele","last_name":"Skase","age":16},
    {"id":226,"name":"Jermain","last_name":"Nemchinov","age":10},
    {"id":227,"name":"Joyous","last_name":"Cartlidge","age":11},
    {"id":228,"name":"Padget","last_name":"Pisco","age":11},
    {"id":229,"name":"Ruben","last_name":"Morison","age":14},
    {"id":230,"name":"Rafaela","last_name":"Lambal","age":18},
    {"id":231,"name":"Lottie","last_name":"Coule","age":10},
    {"id":232,"name":"Jacquelyn","last_name":"Elmhirst","age":17},
    {"id":233,"name":"Elysia","last_name":"Dole","age":13},
    {"id":234,"name":"Inge","last_name":"Leneham","age":16},
    {"id":235,"name":"Kevin","last_name":"Ebbers","age":15},
    {"id":236,"name":"Karlyn","last_name":"Olexa","age":10},
    {"id":237,"name":"Rodrigo","last_name":"Jeannesson","age":12},
    {"id":238,"name":"Ferdinanda","last_name":"Verillo","age":11},
    {"id":239,"name":"Dulcia","last_name":"Stuttard","age":16},
    {"id":240,"name":"Mitchel","last_name":"Stote","age":16},
    {"id":241,"name":"Idalia","last_name":"Boyford","age":13},
    {"id":242,"name":"Monika","last_name":"Heitz","age":15},
    {"id":243,"name":"Angelo","last_name":"Bellhouse","age":16},
    {"id":244,"name":"Kermy","last_name":"Wilcot","age":16},
    {"id":245,"name":"Darryl","last_name":"Beaconsall","age":16},
    {"id":246,"name":"Wilhelmina","last_name":"McRobert","age":13},
    {"id":247,"name":"Ray","last_name":"Bowmaker","age":18},
    {"id":248,"name":"Major","last_name":"Bernini","age":17},
    {"id":249,"name":"Ganny","last_name":"MacGorrie","age":13},
    {"id":250,"name":"Vaughan","last_name":"Massinger","age":14},
    {"id":251,"name":"Barny","last_name":"Syrad","age":13},
    {"id":252,"name":"Faythe","last_name":"Fanthome","age":10},
    {"id":253,"name":"Gwenneth","last_name":"Vlies","age":15},
    {"id":254,"name":"Yoko","last_name":"Schrieves","age":11},
    {"id":255,"name":"Woody","last_name":"Jeandon","age":11},
    {"id":256,"name":"Adelbert","last_name":"Carik","age":10},
    {"id":257,"name":"Jennica","last_name":"Dullaghan","age":12},
    {"id":258,"name":"Andre","last_name":"Saffill","age":11},
    {"id":259,"name":"Carlynne","last_name":"Ollin","age":18},
    {"id":260,"name":"Ardelia","last_name":"Cumming","age":17},
    {"id":261,"name":"Nefen","last_name":"Corry","age":10},
    {"id":262,"name":"Vania","last_name":"Pitt","age":16},
    {"id":263,"name":"Terrijo","last_name":"Hurlston","age":12},
    {"id":264,"name":"Shelden","last_name":"Dasent","age":14},
    {"id":265,"name":"Dalli","last_name":"Tuer","age":15},
    {"id":266,"name":"Dewie","last_name":"Doore","age":12},
    {"id":267,"name":"Patton","last_name":"Banasik","age":10},
    {"id":268,"name":"Koo","last_name":"O'Mahoney","age":15},
    {"id":269,"name":"Diego","last_name":"Tudgay","age":15},
    {"id":270,"name":"Cathyleen","last_name":"Martineau","age":12},
    {"id":271,"name":"Evie","last_name":"Walford","age":16},
    {"id":272,"name":"Donalt","last_name":"Pouck","age":18},
    {"id":273,"name":"Sanford","last_name":"Hallett","age":11},
    {"id":274,"name":"Francois","last_name":"Crimpe","age":13},
    {"id":275,"name":"Ricard","last_name":"Mattiussi","age":11},
    {"id":276,"name":"Allissa","last_name":"Ralling","age":18},
    {"id":277,"name":"Darline","last_name":"Aloigi","age":11},
    {"id":278,"name":"Patricio","last_name":"Mc Corley","age":10},
    {"id":279,"name":"Englebert","last_name":"Ewbanck","age":12},
    {"id":280,"name":"Tremain","last_name":"Klewer","age":14},
    {"id":281,"name":"Braden","last_name":"Bockh","age":17},
    {"id":282,"name":"Weider","last_name":"Blondel","age":13},
    {"id":283,"name":"Ivett","last_name":"Posselwhite","age":10},
    {"id":284,"name":"Ciro","last_name":"Mowatt","age":18},
    {"id":285,"name":"Jocelyn","last_name":"Plesing","age":14},
    {"id":286,"name":"Von","last_name":"Gornal","age":18},
    {"id":287,"name":"Rebecca","last_name":"Lockart","age":11},
    {"id":288,"name":"Lorant","last_name":"Cobon","age":12},
    {"id":289,"name":"Lydie","last_name":"Alessandrucci","age":12},
    {"id":290,"name":"Maddie","last_name":"Franzewitch","age":11},
    {"id":291,"name":"Ottilie","last_name":"Norsister","age":15},
    {"id":292,"name":"Gusty","last_name":"Tolchard","age":14},
    {"id":293,"name":"Cortney","last_name":"Dammarell","age":17},
    {"id":294,"name":"Billi","last_name":"Monteath","age":15},
    {"id":295,"name":"Melamie","last_name":"Purveys","age":11},
    {"id":296,"name":"Janey","last_name":"Tryme","age":17},
    {"id":297,"name":"Terrie","last_name":"Tidd","age":14},
    {"id":298,"name":"Winfield","last_name":"Marrow","age":15},
    {"id":299,"name":"Cecilla","last_name":"Sincock","age":13},
    {"id":300,"name":"Alexia","last_name":"De Benedetti","age":15},
    {"id":301,"name":"Anastassia","last_name":"Borsnall","age":17},
    {"id":302,"name":"Kurt","last_name":"Zemler","age":14},
    {"id":303,"name":"Judye","last_name":"Connors","age":10},
    {"id":304,"name":"Maryanne","last_name":"O' Markey","age":14},
    {"id":305,"name":"Ryan","last_name":"Farlowe","age":16},
    {"id":306,"name":"Valentina","last_name":"Gutman","age":14},
    {"id":307,"name":"Wynny","last_name":"Klimes","age":18},
    {"id":308,"name":"Irma","last_name":"Gritland","age":10},
    {"id":309,"name":"Lawrence","last_name":"Baitson","age":17},
    {"id":310,"name":"Irene","last_name":"Rosenwald","age":17},
    {"id":311,"name":"Myer","last_name":"Doncom","age":17},
    {"id":312,"name":"Kaye","last_name":"Luttger","age":17},
    {"id":313,"name":"Hinda","last_name":"Klima","age":12},
    {"id":314,"name":"Roseanne","last_name":"Haskur","age":11},
    {"id":315,"name":"Philly","last_name":"Clow","age":11},
    {"id":316,"name":"Lillian","last_name":"Tufts","age":11},
    {"id":317,"name":"Courtney","last_name":"Sainte Paul","age":16},
    {"id":318,"name":"Alonzo","last_name":"Mulryan","age":14},
    {"id":319,"name":"Irena","last_name":"Poppy","age":12},
    {"id":320,"name":"Raoul","last_name":"Attwood","age":14},
    {"id":321,"name":"Venita","last_name":"Radke","age":15},
    {"id":322,"name":"Kaiser","last_name":"Brumpton","age":18},
    {"id":323,"name":"Lavena","last_name":"Tynnan","age":18},
    {"id":324,"name":"Orelle","last_name":"Pautard","age":17},
    {"id":325,"name":"Melisande","last_name":"Viel","age":15},
    {"id":326,"name":"Casi","last_name":"Hannen","age":17},
    {"id":327,"name":"Marisa","last_name":"Simons","age":11},
    {"id":328,"name":"Coleen","last_name":"Luca","age":17},
    {"id":329,"name":"Griffith","last_name":"Croizier","age":15},
    {"id":330,"name":"Kriste","last_name":"Vannoort","age":14},
    {"id":331,"name":"Gretta","last_name":"Gleasane","age":15},
    {"id":332,"name":"Lorna","last_name":"Christophle","age":17},
    {"id":333,"name":"Rowland","last_name":"Butner","age":17},
    {"id":334,"name":"Jennie","last_name":"Ingrem","age":12},
    {"id":335,"name":"Selig","last_name":"Colten","age":18},
    {"id":336,"name":"Benjy","last_name":"Kilfedder","age":18},
    {"id":337,"name":"Dari","last_name":"Frankel","age":18},
    {"id":338,"name":"Fara","last_name":"Purkess","age":16},
    {"id":339,"name":"Wilma","last_name":"Adamides","age":17},
    {"id":340,"name":"Dorella","last_name":"Morad","age":10},
    {"id":341,"name":"Harvey","last_name":"Walak","age":16},
    {"id":342,"name":"Karissa","last_name":"Mursell","age":12},
    {"id":343,"name":"Teirtza","last_name":"Soame","age":18},
    {"id":344,"name":"Maressa","last_name":"Obin","age":16},
    {"id":345,"name":"Loren","last_name":"Pawelski","age":13},
    {"id":346,"name":"Efren","last_name":"Brandreth","age":11},
    {"id":347,"name":"Roxanna","last_name":"Arkle","age":15},
    {"id":348,"name":"Alden","last_name":"Morstatt","age":11},
    {"id":349,"name":"Carney","last_name":"Donner","age":14},
    {"id":350,"name":"Orin","last_name":"Phlippsen","age":12},
    {"id":351,"name":"Staford","last_name":"Cole","age":18},
    {"id":352,"name":"Fayette","last_name":"Pescott","age":12},
    {"id":353,"name":"Robinetta","last_name":"MacDougall","age":11},
    {"id":354,"name":"Bernarr","last_name":"Lehrmann","age":16},
    {"id":355,"name":"Jerrylee","last_name":"Gloucester","age":18},
    {"id":356,"name":"Roxie","last_name":"Brannigan","age":10},
    {"id":357,"name":"Arlinda","last_name":"Mourgue","age":13},
    {"id":358,"name":"Hobard","last_name":"Pancoust","age":10},
    {"id":359,"name":"Moshe","last_name":"Erni","age":12},
    {"id":360,"name":"Riva","last_name":"Glanfield","age":17},
    {"id":361,"name":"Arvin","last_name":"Codman","age":11},
    {"id":362,"name":"Gideon","last_name":"Wehner","age":18},
    {"id":363,"name":"Jasen","last_name":"Pinwill","age":17},
    {"id":364,"name":"Berni","last_name":"Sillick","age":12},
    {"id":365,"name":"Guss","last_name":"Arntzen","age":12},
    {"id":366,"name":"Cary","last_name":"Skingle","age":17},
    {"id":367,"name":"Fran","last_name":"Addyman","age":15},
    {"id":368,"name":"Robbie","last_name":"McGrale","age":14},
    {"id":369,"name":"Rochester","last_name":"Trevena","age":17},
    {"id":370,"name":"Wylma","last_name":"Gothliff","age":11},
    {"id":371,"name":"Law","last_name":"Colyer","age":17},
    {"id":372,"name":"Jeffie","last_name":"Edgerley","age":15},
    {"id":373,"name":"Tessie","last_name":"Fretwell","age":11},
    {"id":374,"name":"Georgeanna","last_name":"McFade","age":13},
    {"id":375,"name":"Opal","last_name":"Eldon","age":14},
    {"id":376,"name":"Bradford","last_name":"Pideon","age":15},
    {"id":377,"name":"Lissi","last_name":"Benedick","age":10},
    {"id":378,"name":"Delinda","last_name":"Pettwood","age":18},
    {"id":379,"name":"Johan","last_name":"Polkinghorne","age":11},
    {"id":380,"name":"Kimmi","last_name":"Oldrey","age":11},
    {"id":381,"name":"Emerson","last_name":"Landman","age":11},
    {"id":382,"name":"Waneta","last_name":"Hanham","age":16},
    {"id":383,"name":"Christal","last_name":"Adamsky","age":11},
    {"id":384,"name":"Jacquetta","last_name":"Frunks","age":17},
    {"id":385,"name":"Vere","last_name":"Sumbler","age":13},
    {"id":386,"name":"Alexis","last_name":"Gravenell","age":11},
    {"id":387,"name":"Aloise","last_name":"Canny","age":16},
    {"id":388,"name":"Hillyer","last_name":"Backs","age":15},
    {"id":389,"name":"Danette","last_name":"Archdeacon","age":13},
    {"id":390,"name":"Felice","last_name":"Beazer","age":17},
    {"id":391,"name":"Constantine","last_name":"Cicchinelli","age":15},
    {"id":392,"name":"Jaime","last_name":"Levens","age":13},
    {"id":393,"name":"Ricardo","last_name":"Agutter","age":11},
    {"id":394,"name":"Quinton","last_name":"Casel","age":14},
    {"id":395,"name":"Lion","last_name":"Battleson","age":16},
    {"id":396,"name":"Bibi","last_name":"Tilio","age":15},
    {"id":397,"name":"Cristina","last_name":"Osmond","age":16},
    {"id":398,"name":"Harrie","last_name":"Pristnor","age":18},
    {"id":399,"name":"Jasmine","last_name":"Kildahl","age":14},
    {"id":400,"name":"Lucinda","last_name":"Raymont","age":15},
    {"id":401,"name":"Joachim","last_name":"McBryde","age":10},
    {"id":402,"name":"Tom","last_name":"Caldera","age":10},
    {"id":403,"name":"Zak","last_name":"Laye","age":15},
    {"id":404,"name":"Andra","last_name":"Biffen","age":12},
    {"id":405,"name":"Evyn","last_name":"Hugin","age":14},
    {"id":406,"name":"Udale","last_name":"Shelbourne","age":17},
    {"id":407,"name":"Bale","last_name":"Shilleto","age":10},
    {"id":408,"name":"Celinka","last_name":"Foston","age":10},
    {"id":409,"name":"Meier","last_name":"Learoid","age":18},
    {"id":410,"name":"Helaine","last_name":"Lyfe","age":15},
    {"id":411,"name":"Anthiathia","last_name":"Lamartine","age":11},
    {"id":412,"name":"Aldon","last_name":"Jollie","age":12},
    {"id":413,"name":"Meara","last_name":"Leghorn","age":15},
    {"id":414,"name":"Dallis","last_name":"McGilben","age":15},
    {"id":415,"name":"Xerxes","last_name":"Kliemchen","age":10},
    {"id":416,"name":"Aile","last_name":"Fideler","age":17},
    {"id":417,"name":"Kiley","last_name":"Toller","age":15},
    {"id":418,"name":"Katee","last_name":"Cleaves","age":10},
    {"id":419,"name":"Chloris","last_name":"Dace","age":11},
    {"id":420,"name":"Lucita","last_name":"Buttfield","age":11},
    {"id":421,"name":"Norbie","last_name":"Beacroft","age":14},
    {"id":422,"name":"Toni","last_name":"Reboul","age":13},
    {"id":423,"name":"Patrick","last_name":"Noads","age":18},
    {"id":424,"name":"Heath","last_name":"De Bellis","age":18},
    {"id":425,"name":"Nial","last_name":"Emmanuel","age":15},
    {"id":426,"name":"Charita","last_name":"Thombleson","age":10},
    {"id":427,"name":"Aubree","last_name":"Mungham","age":18},
    {"id":428,"name":"Adrienne","last_name":"Trim","age":11},
    {"id":429,"name":"Christine","last_name":"Pitway","age":17},
    {"id":430,"name":"Tani","last_name":"O' Bee","age":10},
    {"id":431,"name":"Eileen","last_name":"Skayman","age":17},
    {"id":432,"name":"Suzann","last_name":"McLafferty","age":13},
    {"id":433,"name":"Quintin","last_name":"Straker","age":13},
    {"id":434,"name":"Vina","last_name":"Vaggers","age":15},
    {"id":435,"name":"Leandra","last_name":"Bleier","age":14},
    {"id":436,"name":"Gerald","last_name":"Reams","age":10},
    {"id":437,"name":"Helene","last_name":"Beauchop","age":15},
    {"id":438,"name":"Dawna","last_name":"Kitchingman","age":17},
    {"id":439,"name":"Clementia","last_name":"Drake","age":18},
    {"id":440,"name":"Trent","last_name":"Schollar","age":11},
    {"id":441,"name":"Mirella","last_name":"Howell","age":12},
    {"id":442,"name":"Dody","last_name":"Dabney","age":17},
    {"id":443,"name":"Bethany","last_name":"Pude","age":15},
    {"id":444,"name":"Randee","last_name":"Muehler","age":13},
    {"id":445,"name":"George","last_name":"Bencher","age":15},
    {"id":446,"name":"Arlene","last_name":"Onians","age":11},
    {"id":447,"name":"Giraud","last_name":"Anespie","age":16},
    {"id":448,"name":"Madalyn","last_name":"Parnby","age":13},
    {"id":449,"name":"Kendra","last_name":"Reary","age":12},
    {"id":450,"name":"Julina","last_name":"Duggary","age":10},
    {"id":451,"name":"Sancho","last_name":"Kayser","age":12},
    {"id":452,"name":"Hattie","last_name":"Ianizzi","age":18},
    {"id":453,"name":"Lou","last_name":"Freemantle","age":16},
    {"id":454,"name":"Dreddy","last_name":"Rapelli","age":12},
    {"id":455,"name":"Chanda","last_name":"Mantrup","age":11},
    {"id":456,"name":"Blanch","last_name":"Songest","age":14},
    {"id":457,"name":"Faun","last_name":"Lacoste","age":10},
    {"id":458,"name":"Mordecai","last_name":"Denziloe","age":12},
    {"id":459,"name":"Lefty","last_name":"Treagus","age":10},
    {"id":460,"name":"Zelma","last_name":"Gandy","age":11},
    {"id":461,"name":"Kahlil","last_name":"Scrammage","age":18},
    {"id":462,"name":"Sharlene","last_name":"D'Ugo","age":15},
    {"id":463,"name":"Twila","last_name":"Handrok","age":16},
    {"id":464,"name":"Tabor","last_name":"Ruckledge","age":17},
    {"id":465,"name":"Codi","last_name":"Points","age":11},
    {"id":466,"name":"Olva","last_name":"MacNally","age":15},
    {"id":467,"name":"Miriam","last_name":"Corbridge","age":18},
    {"id":468,"name":"Morganne","last_name":"Beernt","age":10},
    {"id":469,"name":"Jolynn","last_name":"Haskur","age":14},
    {"id":470,"name":"Bettye","last_name":"Laughnan","age":18},
    {"id":471,"name":"Ashly","last_name":"Hansmann","age":18},
    {"id":472,"name":"Marylynne","last_name":"Housbey","age":18},
    {"id":473,"name":"Daren","last_name":"Naulls","age":13},
    {"id":474,"name":"Germain","last_name":"Skeel","age":14},
    {"id":475,"name":"Georgy","last_name":"Donat","age":16},
    {"id":476,"name":"Myrilla","last_name":"Kyston","age":16},
    {"id":477,"name":"Aurore","last_name":"Lillegard","age":16},
    {"id":478,"name":"Gayelord","last_name":"Cowdray","age":16},
    {"id":479,"name":"Vic","last_name":"Clutheram","age":14},
    {"id":480,"name":"Rani","last_name":"Tyas","age":12},
    {"id":481,"name":"Kerwin","last_name":"Ricco","age":13},
    {"id":482,"name":"Martin","last_name":"Sympson","age":16},
    {"id":483,"name":"Thayne","last_name":"Woollard","age":17},
    {"id":484,"name":"Mia","last_name":"Mayward","age":16},
    {"id":485,"name":"Madonna","last_name":"Itzkov","age":13},
    {"id":486,"name":"Wendye","last_name":"Spirit","age":18},
    {"id":487,"name":"Ryann","last_name":"Dickson","age":16},
    {"id":488,"name":"Barnaby","last_name":"Hekkert","age":16},
    {"id":489,"name":"Wilmette","last_name":"Coburn","age":11},
    {"id":490,"name":"Saraann","last_name":"Wogden","age":17},
    {"id":491,"name":"Slade","last_name":"Phair","age":18},
    {"id":492,"name":"Adriane","last_name":"Flori","age":11},
    {"id":493,"name":"Cthrine","last_name":"Carne","age":14},
    {"id":494,"name":"Benni","last_name":"Bauduin","age":13},
    {"id":495,"name":"Thedric","last_name":"Norcott","age":16},
    {"id":496,"name":"Kirbee","last_name":"Lorkins","age":10},
    {"id":497,"name":"Levy","last_name":"Bennike","age":15},
    {"id":498,"name":"Marcello","last_name":"Cleworth","age":12},
    {"id":499,"name":"Ammamaria","last_name":"Hollow","age":13},
    {"id":500,"name":"Cosimo","last_name":"Mycock","age":12}]
    const [formData, setFormData] = useState<FormValues>({
      teamName: '',
      age: 16,
      players: selectedPlayers
    });

  const selectablePlayers: Player[] = allPlayers.filter(player => player.age <= formData.age && player.age >= formData.age - 2);

  const [showSelectablePlayers, setShowSelectablePlayers] = useState(false);
 

  function handleInputChange(name: string, value: string) {
    setFormData(prevState => ({
      ...prevState,
      [name]: value
    }));
  }

  function addUserToAttendanceList(playerName: string) {
    const playerToAdd = selectablePlayers.find(player => `${player.name} ${player.last_name}` === playerName);
    if (playerToAdd && !selectedPlayers.includes(playerToAdd)) {
      setSelectedPlayers([...selectedPlayers, playerToAdd]);
      setFormData(prevState => ({
        ...prevState,
        players: [...prevState.players, playerToAdd]
      }));
    }
  }

  function removeUserFromAttendanceList(playerName: string) {
    const updatedSelectedPlayers = selectedPlayers.filter(player => `${player.name} ${player.last_name}` !== playerName);
    setSelectedPlayers(updatedSelectedPlayers);
    setFormData(prevState => ({
      ...prevState,
      players: updatedSelectedPlayers
    }));
  }

  const isPlayerAdded = (player: Player) => {
    return selectedPlayers.some(selectedPlayer => selectedPlayer.id === player.id);
  };

  const myImage = require('../../../../assets/user.png');

  return (
    <AppLayout>
      <View className="w-full h-full">
        <Text className="text-2xl text-center text-white">Create new team</Text>

        <View className='mt-12'>
          <InputField placeholder="team name" placeholderTextColor='light' handleInputChange={(text) => handleInputChange('teamName', text)} name='teamName' additionalStyles='bg-dacka-dark-gray py-3 px-4 rounded-lg my-2' />
          <InputField placeholder="Age" placeholderTextColor='light' handleInputChange={(text) => handleInputChange('age', text)} name='age' additionalStyles='bg-dacka-dark-gray py-3 px-4 rounded-lg my-2' />
        </View>

        {formData.age && (
          <TouchableOpacity onPress={() => setShowSelectablePlayers(prevState => !prevState)} className='px-4 py-3 my-2 rounded-lg bg-dacka-dark-gray'>
            <Text className='text-center text-white'>{showSelectablePlayers ? 'Hide Player List' : 'Show Player List'}</Text>
          </TouchableOpacity>
        )}

        {showSelectablePlayers && (
          <ScrollView className="w-full h-full my-2 rounded-lg bg-dacka-dark-gray">
            {selectablePlayers.map(player => (
              <PlayerCard
                key={player.id}
                name={`${player.name} ${player.last_name}`}
                dateOfBirth={(new Date().getFullYear() - player.age).toString()}
                image={myImage}
                isAdded={isPlayerAdded(player)}
                addUserToAttendanceList={addUserToAttendanceList}
                removeUserFromAttendanceList={removeUserFromAttendanceList}
              />
            ))}
          </ScrollView>
        )}
        <TouchableOpacity className="pr-2" onPress={() => console.log(formData)}>
          <Text className='mt-3 mb-12 text-xl text-right text-white'>Save</Text>
        </TouchableOpacity>
      </View>
    </AppLayout>
  );
};

export default TeamCreationPage;
